version: "3"
services:
  app:
    image: suecharo/dashi:1.0.0
    container_name: dashi
    volumes:
      - ${PWD}:${PWD}
    environment:
      - DASHI_HOST=0.0.0.0
      - DASHI_PORT=8080
      - DASHI_DEBUG=False
      - DASHI_CROS=*
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["dashi"]
