version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agodashi
    container_name: agodashi_dev
    volumes:
      - ${PWD}:${PWD}
    environment:
      - AGODASHI_HOST=0.0.0.0
      - AGODASHI_PORT=8080
      - AGODASHI_DEBUG=True
      - AGODASHI_CROS=*
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["/bin/bash", "./entrypoint.dev.sh"]
