version: "3"
services:
  app:
    image: suecharo/agodashi:1.0.0
    container_name: agodashi
    volumes:
      - ${PWD}:${PWD}
    environment:
      - AGODASHI_HOST=0.0.0.0
      - AGODASHI_PORT=8080
      - AGODASHI_DEBUG=False
      - AGODASHI_CROS=*
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["agodashi"]
