version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashi
    container_name: dashi_dev
    volumes:
      - ${PWD}:${PWD}
    environment:
      - DASHI_HOST=0.0.0.0
      - DASHI_PORT=8080
      - DASHI_DEBUG=True
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["/bin/bash", "./entrypoint.dev.sh"]
